### ISSUE TITLE
Use CSS pseudo classes instead of state here

### ISSUE THREAD

**Issue by ecumene** [SoheilNK/Backgammon#19]
https://github.com/SoheilNK/Backgammon/blob/e019f40bff01cc9400333102fbc20567b0fabc57/src/Dice.tsx#L29

```css
button:hover {
  color: blue;
}
```
